module.exports = {
    dsa: [
        "DFSOnBST",
        "LRU",
        "LinearSearchList",
        "BinarySearchList",
        "ArrayList",
        "BTPreOrder",
        "BTInOrder",
        "BTPostOrder",
        "BTBFS",
        "CompareBinaryTrees",
        "DFSOnBST",
        "DFSGraphList",
        "Trie",
        "BFSGraphMatrix",
        "Map",
        "MinHeap",
    ],
};
